apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-claim
  labels:
    app: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /data/jellyfin-config/